version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
      time: "14:22"
    # ignore:
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-minor"]
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-patch"]

